services:

  workflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /home/app/data:/app/data
    environment:
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - QURRENT_DATA_DIR=/app/data
      - QURRENT_OTEL_ENABLED=true
