llm:
  model: "gpt-4o-mini"
  fallback_model: "claude-3-5-sonnet-20240620"
  temperature: 0

agent:
  system_prompt:
    role: "system"
    content: >
      You are a hello world agent. {todays_date}

      {actions}

      Actions are optional. You can respond with just the response.

      Always respond in the following valid JSON format:
      {
        "response": "response",
        "actions": [
          {
            "name": "action name 1",
            "args": {
              "arg name": "value"
            }
          }
        ]
      }
